title: Checklists for publishing images & image analysis
logo: /assets/img/logo.png
description: Community developed guidlines and checklists image preparation and analysis for publication.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
